### ISSUE TITLE
Error in Maven pom.xml file

### ISSUE THREAD

**Issue by wayner1024** [MafaldaLandeiro/SpringSOAPServiceConsume#1]
I downloaded the zip file, imported it into my eclipse IDE, and had the following error on line 49 of my pom.xml file:

Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate failed: A required class was missing while 
 executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate: com/sun/xml/bind/api/ErrorListener 
----------------------------------------------------- realm = plugin>org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3 strategy = 
 org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy urls[0] ...

...

Any clue as to how to fix this?

**Comment by MafaldaLandeiro** [comment]
Hi,
I believe that is the problem that you are having right?
![problem](https://cloud.githubusercontent.com/assets/3681513/13781070/fbf97860-eab9-11e5-9cfd-c7eb60a3938f.png)
Well, this is a problem that happens on Eclipse, if you use the command line for running maven, you don't have a problem with that. 
I have just update the repository for not having there the generated classes, so when you open on the Eclipse, it will be missing some classes. Then, if you run the mvn compile on your console, you will get success and, after that refresh your eclipse project, and you will have there your generated classes. 
![cmd](https://cloud.githubusercontent.com/assets/3681513/13783620/fec7bd7c-eac3-11e5-8f89-64e02b4030da.png)
I found that solution here: [Issue #6](https://github.com/spring-guides/gs-consuming-web-service/issues/6).
If you will use the first zip, then you may have an error compiling the project, because the classes are already there, so it will be duplicated.
Hope I have helped you fixing the problem. Please, then tell me if that works out for you.
